// app/data.js

export const VENDOR_CREDENTIALS = {
  phone: "9999999999",
};

export const CATEGORIES = [
  { label: "All" },
  { label: "Food & Snacks" },
  { label: "Clothing & Fashion" },
  { label: "Groceries & Kirana" },
  { label: "Electronics & Repair" },
  { label: "Services (Tailoring)" },
  { label: "Jewellery & Makeup" },
  { label: "Stationery" },
];

export const VENDORS = [
  {
    id: 1,
    name: "Raju Samosa Corner",
    category: "Food & Snacks",
    isOpen: true,
    isShop: false,
    lat: 20.2961,
    lng: 85.8245,
    signatureItem: "Samosa",
    signaturePrice: 10,
    chalkboard: "Fresh aloo samosa every evening from 4pm. Chutney free!",
    chalkboardUpdatedAt: new Date(Date.now() - 25 * 60000).toISOString(),
    rating: 4.5,
  },
  {
    id: 2,
    name: "Meena Chaat Bhandar",
    category: "Food & Snacks",
    isOpen: true,
    isShop: false,
    lat: 20.2975,
    lng: 85.826,
    signatureItem: "Pani Puri",
    signaturePrice: 20,
    chalkboard: "Special masala pani puri today. Limited plates!",
    chalkboardUpdatedAt: new Date(Date.now() - 10 * 60000).toISOString(),
    rating: 4.3,
  },
  {
    id: 3,
    name: "Babu Fashion Street",
    category: "Clothing & Fashion",
    isOpen: true,
    isShop: false,
    lat: 20.294,
    lng: 85.823,
    signatureItem: "Oversized Tee",
    signaturePrice: 199,
    chalkboard: "New stock arrived — pastel oversized tees and co-ords.",
    chalkboardUpdatedAt: new Date(Date.now() - 60 * 60000).toISOString(),
    rating: 4.1,
  },
  {
    id: 4,
    name: "Sita Kirana Store",
    category: "Groceries & Kirana",
    isOpen: true,
    isShop: false,
    lat: 20.2955,
    lng: 85.827,
    signatureItem: "Rice (5kg)",
    signaturePrice: 280,
    chalkboard: "Fresh vegetables and dairy restocked this morning.",
    chalkboardUpdatedAt: new Date(Date.now() - 120 * 60000).toISOString(),
    rating: 4.6,
  },
  {
    id: 5,
    name: "Gita Tailoring Works",
    category: "Services (Tailoring)",
    isOpen: false,
    isShop: false,
    lat: 20.2933,
    lng: 85.8255,
    signatureItem: "Blouse Stitching",
    signaturePrice: 150,
    chalkboard: "Festival orders accepted. 3-day delivery guaranteed.",
    chalkboardUpdatedAt: new Date(Date.now() - 3 * 3600000).toISOString(),
    rating: 4.7,
  },
  {
    id: 6,
    name: "Sunita Jewellery & Beauty",
    category: "Jewellery & Makeup",
    isOpen: true,
    isShop: false,
    lat: 20.2968,
    lng: 85.8238,
    signatureItem: "Oxidised Earrings",
    signaturePrice: 120,
    chalkboard: "New kajal and matte lipstick collection in. Come see!",
    chalkboardUpdatedAt: new Date(Date.now() - 45 * 60000).toISOString(),
    rating: 4.4,
  },
  {
    id: 7,
    name: "Pappu Stationery Corner",
    category: "Stationery",
    isOpen: true,
    isShop: false,
    lat: 20.2948,
    lng: 85.8263,
    signatureItem: "Gel Pen Set",
    signaturePrice: 35,
    chalkboard: "Exam season stock ready — geometry boxes, answer sheets.",
    chalkboardUpdatedAt: new Date(Date.now() - 90 * 60000).toISOString(),
    rating: 4.2,
  },
];

// TRENDING is no longer used — replaced by TRENDING_TIPS in i18n.js
export const TRENDING = [];
